name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  bats:
    name: Bats unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install bats
        run: npm --prefix ./tests/ install

      - name: Run
        run: ./tests/node_modules/.bin/bats ./tests/**/*.bats
